name: Typo Check

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  typos:
    name: Check for typos
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run typos check
        uses: crate-ci/typos@v1.34.0
        with:
          config: ./.github/typos_config.toml